Make llama dataset preparatio n more generic.
ROCm/Megatron-LM pull request #32
Opened 2024-12-10 09:37 UTC by lcskrishna

2024-12-10 15:44 UTC, wenchenvincent commented on examples/llama/prepare_dataset.sh
> +    TOKENIZER_MODEL_PATH=meta-llama/Llama-3.1-8B
Do we need the full path here (like for llama2)?

2024-12-10 15:46 UTC, wenchenvincent requested changes
Could you address the comments?

2024-12-10 15:46 UTC, wenchenvincent commented on examples/llama/prepare_dataset.sh
> +python3 ../../tools/preprocess_data.py --input ${DATA_PATH}/bookcorpus_megatron.json  --tokenizer-type GPTSentencePieceTokenizer \
This assumes that we are running in this directory. It is possible that user also run it from other directories like the root directory of the repo. Could you get the directory of this script as the base directory and then use paths relative to the base directory?

2025-01-22 20:41 UTC, wenchenvincent commented
@lcskrishna Do we still need this PR?

2025-01-23 05:48 UTC, lcskrishna commented
> @lcskrishna Do we still need this PR?

Its a clean up task, let me do it in the next few days.

2025-02-12 11:35 UTC, lcskrishna commented
@gurpreet-dhami Can you take over this task, i'm not finding enough time to fix this one.

2025-02-12 11:46 UTC, lcskrishna commented on examples/llama/prepare_dataset.sh
> +    TOKENIZER_MODEL_PATH=meta-llama/Llama-3.1-8B
I don't think its required for llama3

2025-02-13 12:08 UTC, nsakkine commented
@lcskrishna @gurpreet-dhami could we help here? It seems we worked on this concurrently. We prepared [a draft pull-request](https://github.com/ROCm/Megatron-LM/pull/61) just to make our work visible to you. One option would be to go with either pull-request (closing the other). For now, we would have bandwidth to see this through. What do you think?

2025-05-09 14:54 UTC, zstreet87 commented
Closing PR as the other PR mentioned by @nsakkine has already been merged

2025-05-09 14:54 UTC, closed without merging